### ISSUE TITLE
noClassFound Error for PcapPackethandler in Standard Version

### ISSUE THREAD

**Issue by sharlec** [iraffaele/MetroFunnel#1]
Hi, I am currently doing research on microservice monitoring, and I found this interesting tool. I followed the instructions on readme (standard version), but I keep getting java.lang.NoClassDefFoundError.for.PcapPacketHandler. Shall I pre-config libpcap to resolve this error?

I am running MetroFunnel on Ubuntu18.04.1 with java, Docker and libpcap installed.

![image](https://user-images.githubusercontent.com/25064369/87216356-fa06e080-c30c-11ea-8a53-2a78b2ca5e5e.png)

**Comment by iraffaele** [comment]
try running the "install_System_Requirement.sh" command with admin privileges, for example with sudo

make sure that the files in the SystemRequirement folder are copied to your "/usr/lib/" folder

**Comment by sharlec** [comment]
Thanks for the reply and help. I had found the problem is my java is java 11. After I install java 8, the problem solved.
